config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome_pages#show'

  resource  :welcome_page, only: [:show]
  resources :users,        only: [:index, :show]

  resources :posts, only: [:show, :create] do
    resources :comments, only: [:create, :destroy], module: :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author,      optional: true, class_name: :User
  belongs_to :commentable, polymorphic: true
  belongs_to :parent,      optional: true, class_name:'Comment'

  validates :body, presence: true

  # Return child comments for particular comment
  def comments
    Comment.where(commentable: commentable, parent_id: id)
           .order(:created_at)
  end

  # Clear some comment' fields (using in comments#destroy)
  #   because a comment must not be completely removed from a thread
  def clear_fields
    update(author: nil, body: '[deleted]')
  end

  def deleted?
    author.nil?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: :User
  belongs_to :wall
  has_many   :comments, as: :commentable

  validates :body, :author_id, :wall_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one  :wall,     foreign_key: :owner_id
  has_many :posts,    foreign_key: :author_id
  has_many :comments, foreign_key: :author_id

  validates :first_name, :last_name, presence: true, length: { maximum: 25 }

  validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  before_save  { self.email = email.downcase }
  after_create { self.create_wall }
end

app/models/wall.rb
class Wall < ApplicationRecord
  belongs_to :owner, class_name: :User
  has_many   :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, unless: :auth_is_not_required?


  # Return a string that shall be used in a sql query to get a full user's name
  def full_name
    "users.first_name || ' ' || users.last_name"
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,
                                                         :last_name])
    end

  private
    def auth_is_not_required?
      devise_controller? || controller_name == 'welcome_pages'
    end
end

app/controllers/comments_controller.rb
# This class is inhereted by other model' classes that has comments
#   Each one of them define its own @commentable
class CommentsController < ApplicationController
  def create
    @comment        = @commentable.comments.new(comment_params)
    @comment.author = current_user

    # Regardless of a success or failure of the save,
    #   a user must be redirected back to the wall where he tries to comment
    # In case of failure, flash will be used to transmit all neccessary
    #   information to the controller that renders comment' form

    unless @comment.save
      flash[:failed_comment_errors]  = @comment.errors.full_messages
    end

    redirect_to @commentable
  end

  def destroy
    @comment = @commentable.comments.find(params[:id])
    @comment.clear_fields
    redirect_to @commentable
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :parent_id)
    end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable

  private
    # Define an object to which a comment is written
    def set_commentable
      @commentable = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def show
    # Render a parent comment if such is given
    #   otherwise render direct comments of the post

    comment_parameters = if params[:parent_comment]
                           "comments.id = #{ params[:parent_comment] }"
                         else
                           'comments.parent_id IS NULL'
                         end

    @comments = @post.comments
                     .where(comment_parameters)
                     .order(:created_at)
  end

  def create
    @post = Post.new(post_params)

    # Regardless of a success or failure of the save,
    #   a user must be redirected back to the wall where he tries to post
    # In case of failure, flash will be used to transmit all neccessary
    #   information to the controller that renders post' form

    unless @post.save
      flash[:failed_post]        = @post
      flash[:failed_post_errors] = @post.errors.full_messages
    end

    redirect_to user_path(params[:post][:user_id])
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body, :wall_id, :author_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    # Get all users except current
    # And get amount of posts on each user's wall
    @users = Wall.left_outer_joins(:owner, :posts)
                 .select('users.id',
                         "#{full_name} AS name",
                         'count(posts.id) AS posts_amount')
                 .group('users.id')
                 .where("users.id != #{ current_user.id }")
                 .order(:name)
  end

  def show
    @wall = @user.wall

    # ===> This part of code is related to the post creation form
    if flash[:failed_post]
      # If a user already have tried to post and have failed validations
      #   flash contains all neccessary information about that failed post
      @post = Post.new(flash[:failed_post])
    else
      @post = current_user.posts.new(wall_id: @wall.id)
    end
    # <=== end

    # Get all posts on the wall
    #   and all neccessary information to display each post
    # Method .includes isn't used here because there might be a lot of comments
    @posts = Post.left_outer_joins(:author, :comments)
                 .select(
                   :id,
                   :body,
                   :created_at,
                   :author_id,
                   "#{full_name} AS author_name",
                   'count(comments.id) AS comments_amount')
                 .group(:id, :first_name, :last_name)
                 .where(wall_id: @wall.id)
                 .order(:created_at)
                 .reverse_order
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/controllers/welcome_page_controller.rb
class WelcomePageController < ApplicationController
  before_action :allow_only_not_signed_in_users

  def show; end
end

private
  def allow_only_not_signed_in_users
    redirect_to user_path(current_user) if user_signed_in?
  end

app/controllers/welcome_pages_controller.rb
class WelcomePagesController < ApplicationController
  before_action :allow_only_not_signed_in_users

  def show; end

  private
    def allow_only_not_signed_in_users
      redirect_to user_path(current_user) if user_signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ===> Time related helpers <===
  def insert_year_directive_for(obj)
    obj.created_at.year == Time.now.year ? ' ' : ' %Y '
  end

  def formatted_creation_time_of(obj)
    obj.created_at.strftime("%d %b#{ insert_year_directive_for(obj) }at %H:%M")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name(user)
    "#{ user.first_name } #{ user.last_name }"
  end
end

app/helpers/welcome_pages_helper.rb
module WelcomePagesHelper
end

app/views/comments/_comment.html.haml
-# Current comment nesting depth level
- nesting_depth = local_assigns.fetch(:nesting_depth, 1)
-# Amount of comments of one thread that available on one page.
-#   Other comments of the same thread will be moved to a separate page
- nesting_limit = local_assigns[:nesting_limit]

-# Give each thread block an individual id in order to be able anchor any of it
%li{ id: dom_id(comment) }

  -# Block of a single comment
  .message
    .message-body#comment-body
      - if comment.deleted?
        %span.semibold [deleted]
      - else
        %span.semibold= link_to full_name(comment.author), |
                                user_path(comment.author)  |

      %span= link_to '[link to this comment]', url_for(comment: comment.id,
                                                        anchor: dom_id(comment))

      .my-3
        = simple_format comment.body
      %p.grey.mb-3= formatted_creation_time_of(comment)

      -# Block of the reply-to-comment form. Required by stimulus js
      .mt-1{ 'data-controller' => 'reply' }
        -# Button that toggles visibility of the form
        = link_to 'Reply', '#',                             |
                   data: { action: 'click->reply#toggle' }, |
                  class:  'button is-info is-outlined       |
                           button--reply-to-comment'        |
        -# target: the pointer for stimulus to the form
        = render 'comments/form',                            |
                  commentable:  comment.commentable,         |
                       target: 'reply.form',                 |
                        class: 'is-hidden mt-4 is-clearfix', |
                    parent_id:  comment.id                   |

      -# Button to delete comment
      = link_to_if comment.author == current_user,                 |
                   '',                                             |
                  [comment.commentable, comment],                  |
                   method:  :delete,                               |
                     data: { confirm: 'Delete comment?' },         |
                    class:  'fa fa-trash-o button--delete-comment' |

  -# Block that contain children comments of the comment above
  %ul.ml-4{ id: "#{ dom_id(comment) }_comments" }

    -# If nesting depth isn't set or has reached its limit
    -#   move subsequent comments to the next page
    -# Otherwise keep nesting
    - if nesting_limit.present? && (nesting_depth >= nesting_limit)
      = link_to 'Continue this thread ➔',                                      |
                 url_for(parent_comment: comment.id, anchor: dom_id(comment)), |
                 class: 'button is-outlined mb-5 is-info'                      |

    - else
      = render comment.comments, nesting_limit: nesting_limit,    |
                                 nesting_depth: nesting_depth + 1 |

app/views/comments/_form.html.haml
-# Only :model is requred when the form is being rendered as reply-to-post
-# Other stuff is requred when the form is being rendered as reply-to-comment
= form_with model: [commentable, Comment.new],                  |
            local:  true,                                       |
             html:  { class:   local_assigns[:class],           |
                       data: { target: local_assigns[:target] } |
                    } do |f|                                    |

  = f.hidden_field :parent_id, value: local_assigns[:parent_id]

  .field
    .control
      = f.text_area :body,       class: 'textarea is-small mb-4', |
                           placeholder: 'Add a comment'           |

  .field
    .control
      = f.submit 'Comment', class: 'button is-pulled-left is-info |
                                    button--submit-comment'       |

app/views/home/index.html.haml
- if notice
  %p.notification.is-primary= notice
- if alert
  %p.notification.is-danger= alert

app/views/layouts/_head.html.haml
%meta{ content: "text/html; charset=UTF-8, width=device-width, initial-scale=1",
          name: "viewport",
      "http-equiv" => "Content-Type" }
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render 'layouts/head'
    %title VkClone
  %body
    %nav.navbar.is-black.px-6.mb-4
      .navbar-brand
        .navbar-item
          = link_to 'VkClone', root_url,                          |
                     class: 'button is-radiusless title is-black' |
        %a.navbar-burger.burger{ 'data-target' => 'navMenu' }
          %span
          %span
          %span

      .navbar-menu#navMenu
        .navbar-end
          .buttons
            - if user_signed_in?
              = link_to 'Sign out', destroy_user_session_url, method: :delete, |
                         class: 'navbar-item button is-radiusless              |
                                 is-black is-inverted is-outlined'             |
            - else
              = link_to 'Log in', new_user_session_url,            |
                         class: 'navbar-item button is-radiusless  |
                                 is-black is-inverted is-outlined' |
              \
              = link_to 'Sign up', new_user_registration_url,      |
                         class: 'navbar-item button is-radiusless  |
                                 is-black is-inverted is-outlined' |

    .hero.px-4
      .columns{ style: 'justify-content: center'}
        - if user_signed_in?
          .column.is-1.menu-wrap
            %aside.menu
              %ul.menu-list
                %li
                  %a{ href: root_path }
                    %span.icon
                      %i.fa.fa-home
                    %span My page
                %li
                  %a{ href: users_path }
                    %span.icon
                      %i.fa.fa-user
                    %span Users
        .column#mainContentBlock
          = yield

app/views/posts/_form.html.haml
=form_with model: @post, local: true do |f|
  = f.hidden_field :wall_id
  = f.hidden_field :author_id
  = f.hidden_field :user_id, value: params[:id]

  - if flash[:failed_post_errors]
    - input_border = 'is-danger'
    .notification.is-danger
      - flash[:failed_post_errors].each do |msg|
        %p= msg

  .field
    .control
      = f.text_area :body,       class: "textarea is-small #{ input_border }", |
                           placeholder: 'Post something!'                      |

  .field
    .control
      = f.submit 'Post', class: 'button is-pulled-left is-info mt-2 |
                                 button--submit-post'               |

app/views/posts/_post.html.haml
.tile.is-child.box
  %p.title.is-5= link_to post.author_name, user_url(post.author_id)
  %p.subtitle.is-6.grey= formatted_creation_time_of(post)

  %p.content= post.body

  %a.button{ href: post_path(post),
            class: 'is-outlined is-info button--to-post' }
    %span.icon.is-small
      %i.fa.fa-comment-o
    - if post.comments_amount.positive?
      %span= pluralize(post.comments_amount, 'comment')

app/views/posts/show.html.haml
.tile.is-ancestor
  .tile.is-vertical
    .tile.is-parent.is-vertical

      -# Block with a post and additional informaiton
      .tile.is-child.box
        %p.title.is-5= link_to full_name(@post.author), user_url(@post.author)
        %p.subtitle.is-6.grey= formatted_creation_time_of(@post)
        %p.content= @post.body

      -# Block with form for commenting
      .tile.is-child.box.is-clearfix
        = render 'comments/form', commentable: @post

      -# Block that displays errors if comment' form failed validations
      - if flash[:failed_comment_errors]
        .tile.is-child.notification.is-danger
          %p= "Sorry, #{ pluralize(flash[:failed_comment_errors].size,
                'error') } prohibited your comment from being posted"
          - flash[:failed_comment_errors].each do |msg|
            %p= "• #{msg}"

      -# Block with comment threads
      .tile.is-child.box
        %ul
          -# If a user looks at a particular comment thread
          -#   then a page has to contain a link to the original post' page
          - if params[:parent_comment]
            %li.content
              %span Viewing single comment thread.
              = link_to ' View all comments', url_for()

          -# Several blocks of comment threads. Each one contains several
          -#   comment threads that have the same parent (root)
          = render @comments, nesting_limit: PAGE_NESTING_DEPTH_LIMIT_PER_THREAD

app/views/users/index.html.haml
%ul#usersList
  - @users.each do |user|
    %li.pb-2
      %a.box{ href: user_path(user) }
        %span.semibold= user.name
        = "(has #{ pluralize(user.posts_amount, 'post') })"

app/views/users/show.html.haml
.columns
  .column.tile.is-ancestor
    .tile.is-parent.is-vertical

      -# Block with a user' name and additional information about that user
      .tile.is-child.box
        %p.title.is-3= full_name(@user)

      -# Block with only form for posting
      .tile.is-child.box.is-clearfix= render 'posts/form'

      -# Several blocks. Each one contains a single post
      = render @posts

app/views/welcome_pages/show.html.haml
- if notice
  %p.notification.is-primary= notice
- if alert
  %p.notification.is-danger= alert

.notification.has-text-centered
  %p.content.is-large Welcome to VkClone!
  %p.content.is-large Please sign up or log in to continue